backend:
  name: git-gateway
  branch: main # Replace with your default branch

media_folder: "static/images" # Folder for storing uploaded media
public_folder: "/images" # Public path for media files

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog" # Folder where blog posts are stored
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
